* Goals

My primary goal with Emacs is to consolidate the software I use at home. At work, I rely completely on Microsoft's ecosystem and have done what I can to get away from that ecosystem at home. Originally, the intention for my Emacs configuration was to create one environment for all the programming languages I use. As I have familiarized myself with Emacs over the last year and Org mode over the past month or two, I have begun using Emacs for more things. If you're curious about how I'm using emacs, I suggest looking at my =config.org= file. It's broken down by workflow, and each workflow is broken down into the packages that comprise it. My =init.el= file provides the capability to toggle each package on or off based on its =TODO= state. I have two primary reasons for organizing my configuration this way. The first is that, occasionally, when I want to add a new package into my configuration, the package doesn't work as advertised and sometimes it's because of a problem with my setup. Making packages toggle-able makes it easier to debug these issues. The second reason is that I get a strong satisfaction from cleaning out my setup every once in a while. If I want to know what my life would be like without a certain package, being able to toggle my configuration for that package makes this process much easier.

* Installation

This installation documentation is for Emacs 27 on Ubuntu, Debian-based distributions, and other distributions that use apt. There may or may not be some differences in the libraries provided by other package managers. For Emacs to pick up the configuration provided, it should be placed in =~/.config/emacs/=.

Download the [[http://git.savannah.gnu.org/cgit/emacs.git][source code]] and untar it with =tar -xzvf emacs-27.1.tar.gz=. The following command is mostly for me, installing all dependencies for my config in one go. If you want to do things piece-meal, each package section has an install script for its own dependencies. Here's the complete dependency installation script:

#+BEGIN_SRC shell
sudo apt install auctex autoconf fonts-inconsolata fonts-sil-gentium gnupg2 graphviz isync libgif-dev libgnutls28-dev libgtk-3-dev libjpeg-dev libncurses5-dev libotf-dev libpng-dev librsvg2-dev libtiff-dev libwebkit2gtk-4.0-dev libxml2-dev libxpm-dev mu4e postgresql python3-pip python3-venv ripgrep sqlite3 texinfo
#+END_SRC

And here are the minimum requirements for the piece-meal approach:

#+BEGIN_SRC shell
sudo apt install autoconf libgif-dev libgnutls28-dev libgtk-3-dev libjpeg-dev libncurses5-dev libotf-dev libpng-dev librsvg2-dev libtiff-dev libwebkit2gtk-4.0-dev libxml2-dev libxpm-dev
#+END_SRC

Most of the dependencies I can remember my motivation for installing: =libgtk-3-dev=, and =libwebkit2gtk-4.o-dev= are for xwidget support that I wanted for viewing email in a web browser. It doesn't work particularly well, but xwidget support might also be useful for previewing LaTeX documents. I think =libncurses5-dev= is also for xwebkit support. Everything referencing a file extension just provides support for Emacs GUI to render that file type. For the most part, I only wanted support for all of those file extensions because emails have all sorts of things that I wanted to be able to view. The last dependency, =autoconf= is required for running =autogen.sh=. Run =./autogen.sh= from within the source directory to create the configuration script, then run that using =./configure --with-json --with-modules --with-xwidgets --with-rsvg --without-pop= to use the new native JSON parsing and better terminal support with vterm. According to the documentation, --with-json should not be necessary, but I added it for good measure. Once complete, make and install to get everything installed:

#+BEGIN_SRC shell
sudo make && sudo make install
#+END_SRC

On first install, try running =package-refresh-contents= and =package-initialize= within Emacs if you encounter errors. This has fixed things for me in the past.

With everything installed, I suggest moving to [[file:config.org][config.org]] for details on how everything is configured.

* Notes
Anything in the =lisp= directory isn't mine. Org-Gantt is currently maintained [[https://gitlab.com/joukeHijlkema/org-gantt/][here]]. I just have some minor changes to make it render more nicely for me.
